package app.unduit.a2achatapp.models

import android.os.Parcelable
import app.unduit.a2achatapp.helpers.DateHelper
import kotlinx.parcelize.Parcelize

@Parcelize
class PropertyData(

    var uid: String = "",
    var user_id: String? = "",
    var user_name: String? = "",
    var user_picture: String? = "",
    var user_company: String? = "",
    var user_experience: String? = "",
    var user_specialty: List<String>? = null,
    var name: String = "",
    var brn: String = "",
    var verified: Boolean = false,
    var image: Int = 0,
    var selected: Boolean = false,
    var bhk: String = "",
    var price: String = "",
    var sqft: String = "",
    var location: String = "",
    var purpose: String = "",
    var purpose_type: String = "",
    var property_type: String = "",
    var area_community: String = "",
    var project: String = "",
    var bedrooms: String = "",
    var bathrooms: String = "",
    var development_status: String = "",
    var area_size: String = "",
    var maidroom: Boolean = false,
    var balcony: Boolean = false,
    var reqDevelopmentStatus: String = "",
    var occupancy: String = "",
    var furnishing: String = "",
    var reqMaidStatus: String = "",
    var reqBalconyStatus: String = "",
    var service_charge: String = "",
    var floor: String = "",
    var payment_during_construction: String = "",
    var payment_on_handover: String = "",
    var paid_by_owner: String = "",
    var payment_post_handover: String = "",
    var handover_year: String = "",
    var op: String = "",
    var sp: String = "",
    var rented_for: String = "",
    var number_of_checks: String = "",
    var fitting: String = "",
    var payment_method: String = "",
    var purchase_goal: String = "",
    var budget_max: String = "",
    var budget_min: String = "",
    var property_size_min: String = "",
    var property_size_max: String = "",
    var property_moving_time: String = "",
    var property_furniture: String = "",
    var rented_till: String = "",
    var commission: String = "",
    var roi: String = "",
    var negotiation: String = "",
    var property_title: String = "",
    var property_description: String = "",
    var property_images: List<String>? = null,
    var property_status :String="",
    var created_date : String="",
    var sender_id : String="",
    var sender_name : String="",
    var sender_image : String="",
    var sender_phone : String="",
    var sender_whatsapp : String="",
    var user_whatsapp : String="",
    var user_phone : String="",
    var sender_experience : String="",
    var sender_speciality : String="",
    var sender_company : String="",
    var post_type : String = "",

    //Land Data
    var ownership : String = "",
    var gfa : String = "",
    var far : String = "",
    var use : String = "",
    var height : String = "",
    var g_value : String = "",




): Parcelable